# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoEconApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoEconApp

  target 'KakaoEconAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KakaoEconAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
